import { createApp } from 'vue';
import { Icon } from 'vant';
import { Popup } from 'vant';
import { Cell, CellGroup } from 'vant';
import { Col, Row } from 'vant';
import { RadioGroup, Radio } from 'vant';
import { Image as VanImage } from 'vant';
import { Dialog } from 'vant';
import { Loading } from 'vant';
import { Notify } from 'vant';
import App from './App.vue';
import './index.css';
// 2. 引入组件样式
import 'vant/lib/index.css';
// import * as VConsole from "vconsole";
// const vConsole = new VConsole();
const app = createApp(App);
app.use(Icon);
app.use(Popup);
app.use(Cell);
app.use(CellGroup);
app.use(Col);
app.use(Row);
app.use(Radio);
app.use(RadioGroup);
app.use(VanImage);
app.use(Dialog);
app.use(Loading);
app.use(Notify);
app.mount('#root');
